INSERT INTO USERS VALUES(1, 'admin', 'admin');
INSERT INTO USERS VALUES(2, 'user', '12345');

INSERT INTO ROLES VALUES(1, 'ADMIN');
INSERT INTO ROLES VALUES(2, 'USER');

INSERT INTO USERS_ROLES VALUES (1, 1);
INSERT INTO USERS_ROLES VALUES (2, 2);